name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout
        uses: actions/checkout@v2

      #- name: Linting
      #  uses: coherence/action-go-lint@v1

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -count=1 ./...
